name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Start memcached servers
      run: ./tests/setup_tests.sh
      env:
        MEMCACHED_IMAGE: memcached:1.6.45-alpine
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --all-features -- --test-threads=1
